### PR TITLE
Merge codegen and npm-js

### PR DESCRIPTION
**Pull request by andreaTP**

### CODE REVIEW

**Comment by andreaTP** [comment]
This is already on top of #52 .
The publishing and re-use of the local codegen is still missing, but all the rest is already fine (sbt test are already in Circle as well)

**Review by pvlugter — CHANGES_REQUESTED** [review]
Difficult to review something like this, but some suggestions:
 
- We want to keep all the history, so we'll be merging with a merge commit (or possibly a rebase and merge), not a squash and merge. So it would be useful to tidy up the extra commits that have been added (like `test in circleCI`, `more`, `fix`, and so on) so we have as clean a history as possible. It's a shame codegen projects were using merge commits already, rather than squash and merge.
- Rather than having all the earlier commits and then moving their location in an extra commit, rewrite the history now with path renames. Can use `git-filter-repo` for this. For example: `git-filter-repo --path-rename some-path/:codegen/some-path/`. Or even just move everything first when applying to the separate repo, with something like: `git-filter-repo --path-rename :codegen/`. That will make the merged history much easier to follow, as if it was always under `codegen` separately.
- Looks like some commits are not connected to a github user (failing CLA validator) so let's rewrite those commits to have a connected author email.
- I think it's fine to first do the merge with all the code, with renamed paths in the history (as suggested above), and disabled CI, then get everything working in separate pull requests (like #56).

**Comment by andreaTP** [comment]
@pvlugter :

- opened #58 with strictly only the merge of folders
- I followed those instructions: https://github.com/lightbend/akkaserverless-javascript-sdk/issues/30#issuecomment-866133909 if you prefer something to be done differently please go ahead directly with a PR and I will decline the rest
- Not much I can do about those commits other than asking @RoryStokes if he can make sure that all the emails he is committing from are connected to his GH account.
- I'll follow up stacking the rest of the needed changes as soon as we start to merge something

**Comment by pvlugter** [comment]
@andreaTP, I've created a draft of just the npm-js commits in #61, looking to create a cleaner history:
- renamed paths in history to be under `npm-js` and added `npm-js` prefix to all commits
- rebased to remove all the merge commits and have just one linear history
- rewrote Rory's disconnected email address

**Comment by pvlugter** [comment]
Similarly created a cleaner history for codegen in #62.

**Comment by andreaTP** [comment]
Included in #63

**Pull request closed without merging**
