### PR TITLE
bump: akkaserverless-framework 0.7.0-beta.11

### PR DESCRIPTION
**Pull request by patriknw**

### CODE REVIEW

**Comment by andreaTP** [comment]
A few CI errors, but, is the jar published?

> Error downloading com.akkaserverless:akkaserverless-java-sdk:0.7.0-beta.11

**Comment by patriknw** [comment]
They are probably still on their way to maven central. The release build was ok: https://app.circleci.com/pipelines/github/lightbend/akkaserverless-framework/1867/workflows/96d98175-fcc9-48b2-82b5-d64197004b44

**Comment by pvlugter** [comment]
Like Java SDK, this needs the updates to replicated entities. Have created #88 and can take a look at this.

**Comment by pvlugter** [comment]
I've updated the replicated data types in #89. But some other failures as well.

> Error downloading com.akkaserverless:akkaserverless-java-sdk:0.7.0-beta.11

Seems odd that it's downloading the Java SDK. That seems wrong.

Also fails on the integration test for the testkit — doesn't see the proxy log that it's started. Likely a change with the new health check and changes to discovery.

**Comment by patriknw** [comment]
> Also fails on the integration test for the testkit — doesn't see the proxy log that it's started. Likely a change with the new health check and changes to discovery.

I see same in Java SDK. It's looking for log message "Akka Serverless proxy online"
https://github.com/lightbend/akkaserverless-framework/pull/134/files#diff-d5af4489e27710f754d34f93050c5697fd101398ce69c37e6f8b0bcad73d0795R50

**Comment by pvlugter** [comment]
Log message should be changed to `gRPC proxy started` now. Changed here for JS testkit works:  https://github.com/lightbend/akkaserverless-javascript-sdk/pull/89/commits/dd70d4fa6fbcbf60210baa29c088bc8c8e457cc5

**Comment by pvlugter** [comment]
Have fixed the dependency on the Java SDK in #90, and included in #89, which is now passing tests.

**Comment by pvlugter** [comment]
As this needs a bunch of other changes, replacing with #89 which has all of these together now. Will close this one.

**Pull request closed without merging**
