### PR TITLE
bump: update to proxy and protocol 0.7.0-beta.11

### LINKED ISSUE #88: Simplify replicated data types (protocol 0.7.0-beta.11)
In line with the changes to replicated data types in the Akka Serverless protocol from 0.7.0-beta.11 onwards:

- [x] Remove GCounter
- [x] Rename PNCounter to ReplicatedCounter
- [x] Remove GSet
- [x] Rename ORSet to ReplicatedSet
- [x] Rename LWWRegister to ReplicatedRegister
- [x] Rename ORMap to ReplicatedMap
- [x] Remove Flag

### PR DESCRIPTION
**Pull request by pvlugter**
Resolves #88. Includes the bump to 0.7.0-beta.11 from #86. Update the replicated data types in line with the new protocol for replicated entities.

### CODE REVIEW

**Comment by pvlugter** [comment]
Also update to new proxy started log message for integration testkit in https://github.com/lightbend/akkaserverless-javascript-sdk/pull/89/commits/dd70d4fa6fbcbf60210baa29c088bc8c8e457cc5

**Comment by pvlugter** [comment]
Tests all passing now, with the changes from #90 for the codegen build.

**Comment by andreaTP** [comment]
YaY! 🎉 
Great work!

**Review by andreaTP — APPROVED** [review]

**Review by patriknw — APPROVED** [review]
LGTM (brief review)

**Review by johanandren — APPROVED** [review]

**Comment by pvlugter** [comment]
I've rebased to resolve with other changes. Also needed to include the new health check method from #46 as the discovery protocol is typed now, since #77.

**Pull request merged**
