### PR TITLE
Publish native binaries

### PR DESCRIPTION
**Pull request by andreaTP**

### CODE REVIEW

**Comment by andreaTP** [comment]
I attempted but I can't really go any further without major trouble and without merging this and #55 .

My plan would be to:
 - merge everything
 - do a release
 - fix on top whatever is left
 - integrate more tightly e2e tests using the locally built `codegen`
 
 It would be nice if someone can assist me during the process.

**Review by RayRoestenburg — APPROVED** [review]

**Review by pvlugter — COMMENTED** [review]
LGTM.

Looks like a fairly complicated setup, with native images per platform, but when this is for javascript.

Have we changed the artifact names (or similar) now that we've aligned the versions with the SDK version? We'll need to make sure we don't end up with version conflicts at some point.

**Comment by pvlugter** [comment]
Sounds good to first tidy up and merge #55, then get things working and fully integrated on top of that, incrementally.

**Comment by andreaTP** [comment]
Included in #63

**Pull request closed without merging**
