### PR TITLE
Kalix rename

### PR DESCRIPTION
**Pull request by johanandren**
Public API, artifact name changes, doc updates

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
At least one commit author (johan@dianas) is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by lightbend-cla-validator** [comment]
At least one commit author (johan@dianas) is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by lightbend-cla-validator** [comment]
At least one commit author (johan@dianas) is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by johanandren** [comment]
Hmm, samples depend on published akkasls/kalix-scripts which won't be there until this PR has passed. Feels like it should test the scripts version from the project rather, I'll see if I can pull that off.

**Comment by johanandren** [comment]
Docs are now the only thing failing (updated links, site not there yet, link checker failing)

**Pull request merged**
