### PR TITLE
Prettier

### PR DESCRIPTION
**Pull request by andreaTP**
Enforce a consistent code style, in the `sdk` at least.
To enable a proper review I haven't applied the command yet, we can schedule a moment in time to do so.

### CODE REVIEW

**Review by octonato — APPROVED** [review]
Yes, always good to have it.

**Comment by octonato** [comment]
For the record, I applied locally and new format looks good.

**Review by pvlugter — APPROVED** [review]
Yes, good to have automatic formatting. Go ahead and reformat.

**Comment by andreaTP** [comment]
I'll do it, but, I would prefer to first merge #43 given the number of headaches that PR gave me.

**Comment by tsonny** [comment]
YAH!

**Pull request merged**
