### PR TITLE
feat: initial setup for ts

### PR DESCRIPTION
**Pull request by janory**
https://github.com/lightbend/akkaserverless-framework/issues/689

### CODE REVIEW

**Comment by janory** [comment]
@pvlugter @jroper based on the discussion [here](https://github.com/lightbend/akkaserverless-framework/issues/454), I was trying to add a basic TS support to the SDK.

My idea was the following:
- make the whole package TS based with the minimal amount of effort
- try to generate the .d.ts files with the help of the TS compiler based on the existing JSDocs
- gradually extend the JSDocs where the types are missing or not correct

I've faced with the following issues:
I got a couple of TS errors, but I could fix those by removing/adding some parts of the JSDoc (just to make things work).

After that I could create a package locally with `npm pack` and use this package in a simple TS project, where I got intelli sense for the `EventSourcedEntity`:

Screenshot 2021-06-02 at 16 38 01


As you can see here:

Screenshot 2021-06-02 at 16 38 47

unfortunately almost all the types had been inferred to `any` and the `namespace` declarations are also pretty weird.
I think the reason for this is that TS can't handle the module declarations and references (like `@memberOf module:akkaserverless` or `module:akkaserverless.EventSourcedEntity~options=`), that's why the whole type inference stops at first JSDoc comment (`~commandHandler`) and almost everything becomes `any`.

I was also trying to use the `tsd-jsdoc` tool instead of the built in TS compiler to generate the types, but it was failing with these kind of errors:

```
╰─$ node_modules/.bin/jsdoc -t node_modules/tsd-jsdoc/dist -r src/. -d gen_types                                                                                                                                        127 ↵
[TSD-JSDoc] action.js:73:0 Failed to find parent of doclet 'module:akkaserverless.Action' using memberof 'module:akkaserverless', this is likely due to invalid JSDoc.
[TSD-JSDoc] action-support.js:119:2 Failed to find parent of doclet 'ActionHandler#invokeCallback' using memberof 'ActionHandler', this is likely due to invalid JSDoc.
[TSD-JSDoc] action-support.js:135:2 Failed to find parent of doclet 'ActionHandler#passReplyThroughContext' using memberof 'ActionHandler', this is likely due to invalid JSDoc.
[TSD-JSDoc] action.js:73:0 Failed to find parent of doclet 'module:akkaserverless.Action' using memberof 'module:akkaserverless', this is likely due to invalid JSDoc.
[TSD-JSDoc] akkaserverless.js:56:0 Failed to find parent of doclet 'module:akkaserverless.Server' using memberof 'module:akkaserverless', this is likely due to invalid JSDoc.
[TSD-JSDoc] akkaserverless.js:56:0 Failed to find parent of doclet 'module:akkaserverless.Server' using memberof 'module:akkaserverless', this is likely due to invalid JSDoc.
[TSD-JSDoc] akkaserverless.js:84:0 Failed to find parent of doclet 'module:akkaserverless.Entity' using memberof 'module:akkaserverless', this is likely due to invalid JSDoc.
[TSD-JSDoc] akkaserverless.js:98:0 Failed to find parent of doclet 'module:akkaserverless.AkkaServerless' using memberof 'module:akkaserverless', this is likely due to invalid JSDoc.
[TSD-JSDoc] akkaserverless.js:98:0 Failed to find parent of doclet 'module:akkaserverless.AkkaServerless' using memberof 'module:akkaserverless', this is likely due to invalid JSDoc.
[TSD-JSDoc] cloudevents.js:17:0 Failed to find parent of doclet 'module:akkaserverless.CloudEvent' using memberof 'module:akkaserverless', this is likely due to invalid JSDoc.
[TSD-JSDoc] command-helper.js:249:4 Failed to find parent of doclet 'module:akkaserverless.EntityContext' using memberof 'module:akkaserverless', this is likely due to invalid JSDoc.
[TSD-JSDoc] command-helper.js:258:4 Failed to find parent of doclet 'module:akkaserverless.EffectContext' using memberof 'module:akkaserverless', this is likely due to invalid JSDoc.
[TSD-JSDoc] command-helper.js:266:4 Failed to find parent of doclet 'module:akkaserverless.CommandContext' using memberof 'module:akkaserverless', this is likely due to invalid JSDoc.
[TSD-JSDoc] event-sourced-entity.js:100:0 Failed to find parent of doclet 'module:akkaserverless.EventSourcedEntity' using memberof 'module:akkaserverless', this is likely due to invalid JSDoc.
[TSD-JSDoc] event-sourced-entity.js:100:0 Failed to find parent of doclet 'module:akkaserverless.EventSourcedEntity' using memberof 'module:akkaserverless', this is likely due to invalid JSDoc.
[TSD-JSDoc] integration-testkit.js:44:2 Failed to find parent of doclet 'IntegrationTestkit#addComponent' using memberof 'IntegrationTestkit', this is likely due to invalid JSDoc.
[TSD-JSDoc] metadata.js:27:0 Failed to find parent of doclet 'module:akkaserverless.MetadataValue' using memberof 'module:akkaserverless', this is likely due to invalid JSDoc.
[TSD-JSDoc] metadata.js:34:0 Failed to find parent of doclet 'module:akkaserverless.Metadata' using memberof 'module:akkaserverless', this is likely due to invalid JSDoc.
[TSD-JSDoc] protobuf-any.js:39:0 Failed to find parent of doclet 'module:akkaserverless.SerializableProtobufMessage' using memberof 'module:akkaserverless', this is likely due to invalid JSDoc.
[TSD-JSDoc] protobuf-any.js:48:0 Failed to find parent of doclet 'module:akkaserverless.TypedJson' using memberof 'module:akkaserverless', this is likely due to invalid JSDoc.
[TSD-JSDoc] protobuf-any.js:57:0 Failed to find parent of doclet 'module:akkaserverless.Serializable' using memberof 'module:akkaserverless', this is likely due to invalid JSDoc.
[TSD-JSDoc] index.js:31:0 Failed to find parent of doclet 'module:akkaserverless.replicatedentity' using memberof 'module:akkaserverless', this is likely due to invalid JSDoc.
[TSD-JSDoc] ormap.js:182:2 Failed to find parent of doclet '{module:akkaserverless.replicatedentity.ORMap#get}' using memberof '{module:akkaserverless.replicatedentity.ORMap', this is likely due to invalid JSDoc.
[TSD-JSDoc] reply.js:34:2 Failed to find parent of doclet 'Reply#addEffect' using memberof 'Reply', this is likely due to invalid JSDoc.
[TSD-JSDoc] reply.js:45:2 Failed to find parent of doclet 'Reply#addEffects' using memberof 'Reply', this is likely due to invalid JSDoc.
[TSD-JSDoc] reply.js:56:2 Failed to find parent of doclet 'Reply#isEmpty' using memberof 'Reply', this is likely due to invalid JSDoc.
[TSD-JSDoc] reply.js:81:0 Failed to find parent of doclet 'module:akkaserverless.replies' using memberof 'module:akkaserverless', this is likely due to invalid JSDoc.
[TSD-JSDoc] reply.js:93:2 Failed to find parent of doclet 'ReplyFactory#message' using memberof 'ReplyFactory', this is likely due to invalid JSDoc.
[TSD-JSDoc] reply.js:106:2 Failed to find parent of doclet 'ReplyFactory#forward' using memberof 'ReplyFactory', this is likely due to invalid JSDoc.
[TSD-JSDoc] reply.js:120:2 Failed to find parent of doclet 'ReplyFactory#failure' using memberof 'ReplyFactory', this is likely due to invalid JSDoc.
[TSD-JSDoc] reply.js:133:2 Failed to find parent of doclet 'ReplyFactory#noReply' using memberof 'ReplyFactory', this is likely due to invalid JSDoc.
[TSD-JSDoc] value-entity.js:74:0 Failed to find parent of doclet 'module:akkaserverless.ValueEntity' using memberof 'module:akkaserverless', this is likely due to invalid JSDoc.
[TSD-JSDoc] value-entity.js:74:0 Failed to find parent of doclet 'module:akkaserverless.ValueEntity' using memberof 'module:akkaserverless', this is likely due to invalid JSDoc.
[TSD-JSDoc] view.js:59:0 Failed to find parent of doclet 'module:akkaserverless.View' using memberof 'module:akkaserverless', this is likely due to invalid JSDoc.
[TSD-JSDoc] view.js:59:0 Failed to find parent of doclet 'module:akkaserverless.View' using memberof 'module:akkaserverless', this is likely due to invalid JSDoc.
```

For me it looks like that similar to the TS compiler, it has some problems with the module definitions.

At this point I am pretty stuck, because I am not sure how could we reuse the JSDoc comments to generate the TS types, on the other hand as @jroper mentioned starting from scratch would be a lot of work.

It would be nice, if we could find some time to discuss this issue in person or maybe even do some pair programming.
What do you think?

**Comment by pvlugter** [comment]
I don't know about TypeScript or JSDoc. It looks like there are a few open issues for TypeScript around namespaces and `@memberOf`, so it may not be possible. I think it's worthwhile seeing if there is an alternative or better way to structure comments so the types can be derived. Maybe discuss with @johanandren (for same time zone in person chat) to figure out approach going forward?

**Comment by patriknw** [comment]
@RoryStokes Do you have any thoughts about this? https://github.com/lightbend/akkaserverless-javascript-sdk/pull/16#issuecomment-853099397

**Comment by janory** [comment]
adding @katsutoxin to the loop as well

**Comment by katsutoxin** [comment]
@janory , have you tried this solution?  https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html

**Comment by katsutoxin** [comment]
> @janory , have you tried this solution? https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html

If the above solution does not work, you can also try this https://github.com/Microsoft/dts-gen

**Comment by janory** [comment]
> @janory , have you tried this solution? https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html

Yes, this is the solution what we have in this PR, I think the other solution is just same like what the TS compiler does, it's just extracted to a tool from the compiler.

**Comment by katsutoxin** [comment]
> > @janory , have you tried this solution? https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html
> 
> Yes, this is the solution what we have in this PR, I think the other solution is just same like what the TS compiler does, it's just extracted to a tool from the compiler.

Hi @janory ,  `dts-gen` is a totally different solution, usually people use it when compile solution not working.  It simply examines the objects as they appear at runtime, rather than needing the source code that creates the object. 

Here is a demo video for how to use `dts-gen`  https://www.youtube.com/watch?v=ShargpxE1Xs

**Comment by janory** [comment]
Closing this PR and moving on with issue [here](https://github.com/lightbend/akkaserverless-javascript-sdk/pull/22).

**Comment by janory** [comment]
Closing this PR and moving on with the issue [here](https://github.com/lightbend/akkaserverless-javascript-sdk/pull/22).

**Comment by janory** [comment]
> > > @janory , have you tried this solution? https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html
> > 
> > 
> > Yes, this is the solution what we have in this PR, I think the other solution is just same like what the TS compiler does, it's just extracted to a tool from the compiler.
> 
> Hi @janory , `dts-gen` is a totally different solution, usually people use it when compile solution not working. It simply examines the objects as they appear at runtime, rather than needing the source code that creates the object.
> 
> Here is a demo video for how to use `dts-gen` https://www.youtube.com/watch?v=ShargpxE1Xs

fyi @katsutoxin I could eventually move on with the JSDoc -> .d.ts generator, but thanks for the tips and support! 👍 :)

**Pull request closed without merging**
